# -*- coding: utf-8 -*-
"""24-09-02-Hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-8U4bldebSv30MG23adI6cg7QuYwXFJ
"""

print("Hello World")